// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 31 Jul 2020 15:05:18 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raygui

/*
#include "../lib/raygui/src/raygui.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// RAYGUI_VERSION as defined in src/raygui.h:134
	RAYGUI_VERSION = "2.6-dev"
	// RAYGUIDEF as defined in src/raygui.h:148
	RAYGUIDEF = 0
	// NUM_CONTROLS as defined in src/raygui.h:180
	NUM_CONTROLS = 16
	// NUM_PROPS_DEFAULT as defined in src/raygui.h:181
	NUM_PROPS_DEFAULT = 16
	// NUM_PROPS_EXTENDED as defined in src/raygui.h:182
	NUM_PROPS_EXTENDED = 8
	// TEXTEDIT_CURSOR_BLINK_FRAMES as defined in src/raygui.h:184
	TEXTEDIT_CURSOR_BLINK_FRAMES = 20
)

// GuiControlState as declared in src/raygui.h:264
type GuiControlState int32

// GuiControlState enumeration from src/raygui.h:264
const (
	GUI_STATE_NORMAL   GuiControlState = iota
	GUI_STATE_FOCUSED  GuiControlState = 1
	GUI_STATE_PRESSED  GuiControlState = 2
	GUI_STATE_DISABLED GuiControlState = 3
)

// GuiTextAlignment as declared in src/raygui.h:271
type GuiTextAlignment int32

// GuiTextAlignment enumeration from src/raygui.h:271
const (
	GUI_TEXT_ALIGN_LEFT   GuiTextAlignment = iota
	GUI_TEXT_ALIGN_CENTER GuiTextAlignment = 1
	GUI_TEXT_ALIGN_RIGHT  GuiTextAlignment = 2
)

// GuiControl as declared in src/raygui.h:291
type GuiControl int32

// GuiControl enumeration from src/raygui.h:291
const (
	DEFAULT     GuiControl = iota
	LABEL       GuiControl = 1
	BUTTON      GuiControl = 2
	TOGGLE      GuiControl = 3
	SLIDER      GuiControl = 4
	PROGRESSBAR GuiControl = 5
	CHECKBOX    GuiControl = 6
	COMBOBOX    GuiControl = 7
	DROPDOWNBOX GuiControl = 8
	TEXTBOX     GuiControl = 9
	VALUEBOX    GuiControl = 10
	SPINNER     GuiControl = 11
	LISTVIEW    GuiControl = 12
	COLORPICKER GuiControl = 13
	SCROLLBAR   GuiControl = 14
	STATUSBAR   GuiControl = 15
)

// GuiControlProperty as declared in src/raygui.h:311
type GuiControlProperty int32

// GuiControlProperty enumeration from src/raygui.h:311
const (
	BORDER_COLOR_NORMAL   GuiControlProperty = iota
	BASE_COLOR_NORMAL     GuiControlProperty = 1
	TEXT_COLOR_NORMAL     GuiControlProperty = 2
	BORDER_COLOR_FOCUSED  GuiControlProperty = 3
	BASE_COLOR_FOCUSED    GuiControlProperty = 4
	TEXT_COLOR_FOCUSED    GuiControlProperty = 5
	BORDER_COLOR_PRESSED  GuiControlProperty = 6
	BASE_COLOR_PRESSED    GuiControlProperty = 7
	TEXT_COLOR_PRESSED    GuiControlProperty = 8
	BORDER_COLOR_DISABLED GuiControlProperty = 9
	BASE_COLOR_DISABLED   GuiControlProperty = 10
	TEXT_COLOR_DISABLED   GuiControlProperty = 11
	BORDER_WIDTH          GuiControlProperty = 12
	TEXT_PADDING          GuiControlProperty = 13
	TEXT_ALIGNMENT        GuiControlProperty = 14
	RESERVED              GuiControlProperty = 15
)

// GuiDefaultProperty as declared in src/raygui.h:322
type GuiDefaultProperty int32

// GuiDefaultProperty enumeration from src/raygui.h:322
const (
	TEXT_SIZE        GuiDefaultProperty = 16
	TEXT_SPACING     GuiDefaultProperty = 17
	LINE_COLOR       GuiDefaultProperty = 18
	BACKGROUND_COLOR GuiDefaultProperty = 19
)

// GuiToggleProperty as declared in src/raygui.h:333
type GuiToggleProperty int32

// GuiToggleProperty enumeration from src/raygui.h:333
const (
	GROUP_PADDING GuiToggleProperty = 16
)

// GuiSliderProperty as declared in src/raygui.h:339
type GuiSliderProperty int32

// GuiSliderProperty enumeration from src/raygui.h:339
const (
	SLIDER_WIDTH   GuiSliderProperty = 16
	SLIDER_PADDING GuiSliderProperty = 17
)

// GuiProgressBarProperty as declared in src/raygui.h:344
type GuiProgressBarProperty int32

// GuiProgressBarProperty enumeration from src/raygui.h:344
const (
	PROGRESS_PADDING GuiProgressBarProperty = 16
)

// GuiCheckBoxProperty as declared in src/raygui.h:349
type GuiCheckBoxProperty int32

// GuiCheckBoxProperty enumeration from src/raygui.h:349
const (
	CHECK_PADDING GuiCheckBoxProperty = 16
)

// GuiComboBoxProperty as declared in src/raygui.h:355
type GuiComboBoxProperty int32

// GuiComboBoxProperty enumeration from src/raygui.h:355
const (
	COMBO_BUTTON_WIDTH   GuiComboBoxProperty = 16
	COMBO_BUTTON_PADDING GuiComboBoxProperty = 17
)

// GuiDropdownBoxProperty as declared in src/raygui.h:361
type GuiDropdownBoxProperty int32

// GuiDropdownBoxProperty enumeration from src/raygui.h:361
const (
	ARROW_PADDING          GuiDropdownBoxProperty = 16
	DROPDOWN_ITEMS_PADDING GuiDropdownBoxProperty = 17
)

// GuiTextBoxProperty as declared in src/raygui.h:369
type GuiTextBoxProperty int32

// GuiTextBoxProperty enumeration from src/raygui.h:369
const (
	TEXT_INNER_PADDING GuiTextBoxProperty = 16
	TEXT_LINES_PADDING GuiTextBoxProperty = 17
	COLOR_SELECTED_FG  GuiTextBoxProperty = 18
	COLOR_SELECTED_BG  GuiTextBoxProperty = 19
)

// GuiSpinnerProperty as declared in src/raygui.h:375
type GuiSpinnerProperty int32

// GuiSpinnerProperty enumeration from src/raygui.h:375
const (
	SPIN_BUTTON_WIDTH   GuiSpinnerProperty = 16
	SPIN_BUTTON_PADDING GuiSpinnerProperty = 17
)

// GuiScrollBarProperty as declared in src/raygui.h:385
type GuiScrollBarProperty int32

// GuiScrollBarProperty enumeration from src/raygui.h:385
const (
	ARROWS_SIZE           GuiScrollBarProperty = 16
	ARROWS_VISIBLE        GuiScrollBarProperty = 17
	SCROLL_SLIDER_PADDING GuiScrollBarProperty = 18
	SCROLL_SLIDER_SIZE    GuiScrollBarProperty = 19
	SCROLL_PADDING        GuiScrollBarProperty = 20
	SCROLL_SPEED          GuiScrollBarProperty = 21
)

// GuiScrollBarSide as declared in src/raygui.h:391
type GuiScrollBarSide int32

// GuiScrollBarSide enumeration from src/raygui.h:391
const (
	SCROLLBAR_LEFT_SIDE  GuiScrollBarSide = iota
	SCROLLBAR_RIGHT_SIDE GuiScrollBarSide = 1
)

// GuiListViewProperty as declared in src/raygui.h:399
type GuiListViewProperty int32

// GuiListViewProperty enumeration from src/raygui.h:399
const (
	LIST_ITEMS_HEIGHT  GuiListViewProperty = 16
	LIST_ITEMS_PADDING GuiListViewProperty = 17
	SCROLLBAR_WIDTH    GuiListViewProperty = 18
	SCROLLBAR_SIDE     GuiListViewProperty = 19
)

// GuiColorPickerProperty as declared in src/raygui.h:408
type GuiColorPickerProperty int32

// GuiColorPickerProperty enumeration from src/raygui.h:408
const (
	COLOR_SELECTOR_SIZE      GuiColorPickerProperty = 16
	HUEBAR_WIDTH             GuiColorPickerProperty = 17
	HUEBAR_PADDING           GuiColorPickerProperty = 18
	HUEBAR_SELECTOR_HEIGHT   GuiColorPickerProperty = 19
	HUEBAR_SELECTOR_OVERFLOW GuiColorPickerProperty = 20
)

// FontType as declared in src/raylib.h:804
type FontType int32

// FontType enumeration from src/raylib.h:804
const (
	FONT_DEFAULT FontType = iota
)
