// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 07 Aug 2020 20:59:34 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raygui provides Go bindings for Raygui.
*/
package raygui
