// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 30 Aug 2020 12:21:55 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raygui provides Go bindings for Raygui.
*/
package raygui
