// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Jul 2020 04:51:39 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../lib/raylib/src/raylib.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

