// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Jun 2021 11:29:38 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../lib/raylib/src/raylib.h"
#include "../lib/raylib/src/raymath.h"
#include "../lib/raylib/src/easings.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

