// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 22 Aug 2020 07:53:20 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../lib/raylib/src/raylib.h"
#include "../lib/raylib/src/raymath.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

