// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 19 May 2021 16:47:16 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raylib

/*
#include "../lib/raylib/src/raylib.h"
#include "../lib/raylib/src/raymath.h"
#include "../lib/raylib/src/rlgl.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// PI as defined in src/raylib.h:103
	PI = 3.14159265358979323846
	// DEG2RAD as defined in src/raylib.h:106
	DEG2RAD = (PI / 180.0)
	// RAD2DEG as defined in src/raylib.h:107
	RAD2DEG = (180.0 / PI)
)

// ConfigFlags as declared in src/raylib.h:511
type ConfigFlags int32

// ConfigFlags enumeration from src/raylib.h:511
const (
	FLAG_VSYNC_HINT         ConfigFlags = 0x00000040
	FLAG_FULLSCREEN_MODE    ConfigFlags = 0x00000002
	FLAG_WINDOW_RESIZABLE   ConfigFlags = 0x00000004
	FLAG_WINDOW_UNDECORATED ConfigFlags = 0x00000008
	FLAG_WINDOW_HIDDEN      ConfigFlags = 0x00000080
	FLAG_WINDOW_MINIMIZED   ConfigFlags = 0x00000200
	FLAG_WINDOW_MAXIMIZED   ConfigFlags = 0x00000400
	FLAG_WINDOW_UNFOCUSED   ConfigFlags = 0x00000800
	FLAG_WINDOW_TOPMOST     ConfigFlags = 0x00001000
	FLAG_WINDOW_ALWAYS_RUN  ConfigFlags = 0x00000100
	FLAG_WINDOW_TRANSPARENT ConfigFlags = 0x00000010
	FLAG_WINDOW_HIGHDPI     ConfigFlags = 0x00002000
	FLAG_MSAA_4X_HINT       ConfigFlags = 0x00000020
	FLAG_INTERLACED_HINT    ConfigFlags = 0x00010000
)

// KeyboardKey as declared in src/raylib.h:645
type KeyboardKey int32

// KeyboardKey enumeration from src/raylib.h:645
const (
	KEY_NULL          KeyboardKey = iota
	KEY_APOSTROPHE    KeyboardKey = 39
	KEY_COMMA         KeyboardKey = 44
	KEY_MINUS         KeyboardKey = 45
	KEY_PERIOD        KeyboardKey = 46
	KEY_SLASH         KeyboardKey = 47
	KEY_ZERO          KeyboardKey = 48
	KEY_ONE           KeyboardKey = 49
	KEY_TWO           KeyboardKey = 50
	KEY_THREE         KeyboardKey = 51
	KEY_FOUR          KeyboardKey = 52
	KEY_FIVE          KeyboardKey = 53
	KEY_SIX           KeyboardKey = 54
	KEY_SEVEN         KeyboardKey = 55
	KEY_EIGHT         KeyboardKey = 56
	KEY_NINE          KeyboardKey = 57
	KEY_SEMICOLON     KeyboardKey = 59
	KEY_EQUAL         KeyboardKey = 61
	KEY_A             KeyboardKey = 65
	KEY_B             KeyboardKey = 66
	KEY_C             KeyboardKey = 67
	KEY_D             KeyboardKey = 68
	KEY_E             KeyboardKey = 69
	KEY_F             KeyboardKey = 70
	KEY_G             KeyboardKey = 71
	KEY_H             KeyboardKey = 72
	KEY_I             KeyboardKey = 73
	KEY_J             KeyboardKey = 74
	KEY_K             KeyboardKey = 75
	KEY_L             KeyboardKey = 76
	KEY_M             KeyboardKey = 77
	KEY_N             KeyboardKey = 78
	KEY_O             KeyboardKey = 79
	KEY_P             KeyboardKey = 80
	KEY_Q             KeyboardKey = 81
	KEY_R             KeyboardKey = 82
	KEY_S             KeyboardKey = 83
	KEY_T             KeyboardKey = 84
	KEY_U             KeyboardKey = 85
	KEY_V             KeyboardKey = 86
	KEY_W             KeyboardKey = 87
	KEY_X             KeyboardKey = 88
	KEY_Y             KeyboardKey = 89
	KEY_Z             KeyboardKey = 90
	KEY_SPACE         KeyboardKey = 32
	KEY_ESCAPE        KeyboardKey = 256
	KEY_ENTER         KeyboardKey = 257
	KEY_TAB           KeyboardKey = 258
	KEY_BACKSPACE     KeyboardKey = 259
	KEY_INSERT        KeyboardKey = 260
	KEY_DELETE        KeyboardKey = 261
	KEY_RIGHT         KeyboardKey = 262
	KEY_LEFT          KeyboardKey = 263
	KEY_DOWN          KeyboardKey = 264
	KEY_UP            KeyboardKey = 265
	KEY_PAGE_UP       KeyboardKey = 266
	KEY_PAGE_DOWN     KeyboardKey = 267
	KEY_HOME          KeyboardKey = 268
	KEY_END           KeyboardKey = 269
	KEY_CAPS_LOCK     KeyboardKey = 280
	KEY_SCROLL_LOCK   KeyboardKey = 281
	KEY_NUM_LOCK      KeyboardKey = 282
	KEY_PRINT_SCREEN  KeyboardKey = 283
	KEY_PAUSE         KeyboardKey = 284
	KEY_F1            KeyboardKey = 290
	KEY_F2            KeyboardKey = 291
	KEY_F3            KeyboardKey = 292
	KEY_F4            KeyboardKey = 293
	KEY_F5            KeyboardKey = 294
	KEY_F6            KeyboardKey = 295
	KEY_F7            KeyboardKey = 296
	KEY_F8            KeyboardKey = 297
	KEY_F9            KeyboardKey = 298
	KEY_F10           KeyboardKey = 299
	KEY_F11           KeyboardKey = 300
	KEY_F12           KeyboardKey = 301
	KEY_LEFT_SHIFT    KeyboardKey = 340
	KEY_LEFT_CONTROL  KeyboardKey = 341
	KEY_LEFT_ALT      KeyboardKey = 342
	KEY_LEFT_SUPER    KeyboardKey = 343
	KEY_RIGHT_SHIFT   KeyboardKey = 344
	KEY_RIGHT_CONTROL KeyboardKey = 345
	KEY_RIGHT_ALT     KeyboardKey = 346
	KEY_RIGHT_SUPER   KeyboardKey = 347
	KEY_KB_MENU       KeyboardKey = 348
	KEY_LEFT_BRACKET  KeyboardKey = 91
	KEY_BACKSLASH     KeyboardKey = 92
	KEY_RIGHT_BRACKET KeyboardKey = 93
	KEY_GRAVE         KeyboardKey = 96
	KEY_KP_0          KeyboardKey = 320
	KEY_KP_1          KeyboardKey = 321
	KEY_KP_2          KeyboardKey = 322
	KEY_KP_3          KeyboardKey = 323
	KEY_KP_4          KeyboardKey = 324
	KEY_KP_5          KeyboardKey = 325
	KEY_KP_6          KeyboardKey = 326
	KEY_KP_7          KeyboardKey = 327
	KEY_KP_8          KeyboardKey = 328
	KEY_KP_9          KeyboardKey = 329
	KEY_KP_DECIMAL    KeyboardKey = 330
	KEY_KP_DIVIDE     KeyboardKey = 331
	KEY_KP_MULTIPLY   KeyboardKey = 332
	KEY_KP_SUBTRACT   KeyboardKey = 333
	KEY_KP_ADD        KeyboardKey = 334
	KEY_KP_ENTER      KeyboardKey = 335
	KEY_KP_EQUAL      KeyboardKey = 336
	KEY_BACK          KeyboardKey = 4
	KEY_MENU          KeyboardKey = 82
	KEY_VOLUME_UP     KeyboardKey = 24
	KEY_VOLUME_DOWN   KeyboardKey = 25
)

// MouseButton as declared in src/raylib.h:662
type MouseButton int32

// MouseButton enumeration from src/raylib.h:662
const (
	MOUSE_BUTTON_LEFT    MouseButton = iota
	MOUSE_BUTTON_RIGHT   MouseButton = 1
	MOUSE_BUTTON_MIDDLE  MouseButton = 2
	MOUSE_BUTTON_SIDE    MouseButton = 3
	MOUSE_BUTTON_EXTRA   MouseButton = 4
	MOUSE_BUTTON_FORWARD MouseButton = 5
	MOUSE_BUTTON_BACK    MouseButton = 6
	MOUSE_BUTTON_MAX     MouseButton = 7
)

// MouseCursor as declared in src/raylib.h:677
type MouseCursor int32

// MouseCursor enumeration from src/raylib.h:677
const (
	MOUSE_CURSOR_DEFAULT       MouseCursor = iota
	MOUSE_CURSOR_ARROW         MouseCursor = 1
	MOUSE_CURSOR_IBEAM         MouseCursor = 2
	MOUSE_CURSOR_CROSSHAIR     MouseCursor = 3
	MOUSE_CURSOR_POINTING_HAND MouseCursor = 4
	MOUSE_CURSOR_RESIZE_EW     MouseCursor = 5
	MOUSE_CURSOR_RESIZE_NS     MouseCursor = 6
	MOUSE_CURSOR_RESIZE_NWSE   MouseCursor = 7
	MOUSE_CURSOR_RESIZE_NESW   MouseCursor = 8
	MOUSE_CURSOR_RESIZE_ALL    MouseCursor = 9
	MOUSE_CURSOR_NOT_ALLOWED   MouseCursor = 10
)

// GamepadButton as declared in src/raylib.h:713
type GamepadButton int32

// GamepadButton enumeration from src/raylib.h:713
const (
	GAMEPAD_BUTTON_UNKNOWN          GamepadButton = iota
	GAMEPAD_BUTTON_LEFT_FACE_UP     GamepadButton = 1
	GAMEPAD_BUTTON_LEFT_FACE_RIGHT  GamepadButton = 2
	GAMEPAD_BUTTON_LEFT_FACE_DOWN   GamepadButton = 3
	GAMEPAD_BUTTON_LEFT_FACE_LEFT   GamepadButton = 4
	GAMEPAD_BUTTON_RIGHT_FACE_UP    GamepadButton = 5
	GAMEPAD_BUTTON_RIGHT_FACE_RIGHT GamepadButton = 6
	GAMEPAD_BUTTON_RIGHT_FACE_DOWN  GamepadButton = 7
	GAMEPAD_BUTTON_RIGHT_FACE_LEFT  GamepadButton = 8
	GAMEPAD_BUTTON_LEFT_TRIGGER_1   GamepadButton = 9
	GAMEPAD_BUTTON_LEFT_TRIGGER_2   GamepadButton = 10
	GAMEPAD_BUTTON_RIGHT_TRIGGER_1  GamepadButton = 11
	GAMEPAD_BUTTON_RIGHT_TRIGGER_2  GamepadButton = 12
	GAMEPAD_BUTTON_MIDDLE_LEFT      GamepadButton = 13
	GAMEPAD_BUTTON_MIDDLE           GamepadButton = 14
	GAMEPAD_BUTTON_MIDDLE_RIGHT     GamepadButton = 15
	GAMEPAD_BUTTON_LEFT_THUMB       GamepadButton = 16
	GAMEPAD_BUTTON_RIGHT_THUMB      GamepadButton = 17
)

// GamepadAxis as declared in src/raylib.h:728
type GamepadAxis int32

// GamepadAxis enumeration from src/raylib.h:728
const (
	GAMEPAD_AXIS_LEFT_X        GamepadAxis = iota
	GAMEPAD_AXIS_LEFT_Y        GamepadAxis = 1
	GAMEPAD_AXIS_RIGHT_X       GamepadAxis = 2
	GAMEPAD_AXIS_RIGHT_Y       GamepadAxis = 3
	GAMEPAD_AXIS_LEFT_TRIGGER  GamepadAxis = 4
	GAMEPAD_AXIS_RIGHT_TRIGGER GamepadAxis = 5
)

// MaterialMapIndex as declared in src/raylib.h:743
type MaterialMapIndex int32

// MaterialMapIndex enumeration from src/raylib.h:743
const (
	MATERIAL_MAP_ALBEDO     MaterialMapIndex = iota
	MATERIAL_MAP_METALNESS  MaterialMapIndex = 1
	MATERIAL_MAP_NORMAL     MaterialMapIndex = 2
	MATERIAL_MAP_ROUGHNESS  MaterialMapIndex = 3
	MATERIAL_MAP_OCCLUSION  MaterialMapIndex = 4
	MATERIAL_MAP_EMISSION   MaterialMapIndex = 5
	MATERIAL_MAP_HEIGHT     MaterialMapIndex = 6
	MATERIAL_MAP_BRDG       MaterialMapIndex = 7
	MATERIAL_MAP_CUBEMAP    MaterialMapIndex = 8
	MATERIAL_MAP_IRRADIANCE MaterialMapIndex = 9
	MATERIAL_MAP_PREFILTER  MaterialMapIndex = 10
)

// ShaderLocationIndex as declared in src/raylib.h:776
type ShaderLocationIndex int32

// ShaderLocationIndex enumeration from src/raylib.h:776
const (
	SHADER_LOC_VERTEX_POSITION   ShaderLocationIndex = iota
	SHADER_LOC_VERTEX_TEXCOORD01 ShaderLocationIndex = 1
	SHADER_LOC_VERTEX_TEXCOORD02 ShaderLocationIndex = 2
	SHADER_LOC_VERTEX_NORMAL     ShaderLocationIndex = 3
	SHADER_LOC_VERTEX_TANGENT    ShaderLocationIndex = 4
	SHADER_LOC_VERTEX_COLOR      ShaderLocationIndex = 5
	SHADER_LOC_MATRIX_MVP        ShaderLocationIndex = 6
	SHADER_LOC_MATRIX_VIEW       ShaderLocationIndex = 7
	SHADER_LOC_MATRIX_PROJECTION ShaderLocationIndex = 8
	SHADER_LOC_MATRIX_MODEL      ShaderLocationIndex = 9
	SHADER_LOC_MATRIX_NORMAL     ShaderLocationIndex = 10
	SHADER_LOC_VECTOR_VIEW       ShaderLocationIndex = 11
	SHADER_LOC_COLOR_DIFFUSE     ShaderLocationIndex = 12
	SHADER_LOC_COLOR_SPECULAR    ShaderLocationIndex = 13
	SHADER_LOC_COLOR_AMBIENT     ShaderLocationIndex = 14
	SHADER_LOC_MAP_ALBEDO        ShaderLocationIndex = 15
	SHADER_LOC_MAP_METALNESS     ShaderLocationIndex = 16
	SHADER_LOC_MAP_NORMAL        ShaderLocationIndex = 17
	SHADER_LOC_MAP_ROUGHNESS     ShaderLocationIndex = 18
	SHADER_LOC_MAP_OCCLUSION     ShaderLocationIndex = 19
	SHADER_LOC_MAP_EMISSION      ShaderLocationIndex = 20
	SHADER_LOC_MAP_HEIGHT        ShaderLocationIndex = 21
	SHADER_LOC_MAP_CUBEMAP       ShaderLocationIndex = 22
	SHADER_LOC_MAP_IRRADIANCE    ShaderLocationIndex = 23
	SHADER_LOC_MAP_PREFILTER     ShaderLocationIndex = 24
	SHADER_LOC_MAP_BRDF          ShaderLocationIndex = 25
)

// ShaderUniformDataType as declared in src/raylib.h:792
type ShaderUniformDataType int32

// ShaderUniformDataType enumeration from src/raylib.h:792
const (
	SHADER_UNIFORM_FLOAT     ShaderUniformDataType = iota
	SHADER_UNIFORM_VEC2      ShaderUniformDataType = 1
	SHADER_UNIFORM_VEC3      ShaderUniformDataType = 2
	SHADER_UNIFORM_VEC4      ShaderUniformDataType = 3
	SHADER_UNIFORM_INT       ShaderUniformDataType = 4
	SHADER_UNIFORM_IVEC2     ShaderUniformDataType = 5
	SHADER_UNIFORM_IVEC3     ShaderUniformDataType = 6
	SHADER_UNIFORM_IVEC4     ShaderUniformDataType = 7
	SHADER_UNIFORM_SAMPLER2D ShaderUniformDataType = 8
)

// PixelFormat as declared in src/raylib.h:818
type PixelFormat int32

// PixelFormat enumeration from src/raylib.h:818
const (
	PIXELFORMAT_UNCOMPRESSED_GRAYSCALE    PixelFormat = 1
	PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA   PixelFormat = 2
	PIXELFORMAT_UNCOMPRESSED_R5G6B5       PixelFormat = 3
	PIXELFORMAT_UNCOMPRESSED_R8G8B8       PixelFormat = 4
	PIXELFORMAT_UNCOMPRESSED_R5G5B5A1     PixelFormat = 5
	PIXELFORMAT_UNCOMPRESSED_R4G4B4A4     PixelFormat = 6
	PIXELFORMAT_UNCOMPRESSED_R8G8B8A8     PixelFormat = 7
	PIXELFORMAT_UNCOMPRESSED_R32          PixelFormat = 8
	PIXELFORMAT_UNCOMPRESSED_R32G32B32    PixelFormat = 9
	PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 PixelFormat = 10
	PIXELFORMAT_COMPRESSED_DXT1_RGB       PixelFormat = 11
	PIXELFORMAT_COMPRESSED_DXT1_RGBA      PixelFormat = 12
	PIXELFORMAT_COMPRESSED_DXT3_RGBA      PixelFormat = 13
	PIXELFORMAT_COMPRESSED_DXT5_RGBA      PixelFormat = 14
	PIXELFORMAT_COMPRESSED_ETC1_RGB       PixelFormat = 15
	PIXELFORMAT_COMPRESSED_ETC2_RGB       PixelFormat = 16
	PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA  PixelFormat = 17
	PIXELFORMAT_COMPRESSED_PVRT_RGB       PixelFormat = 18
	PIXELFORMAT_COMPRESSED_PVRT_RGBA      PixelFormat = 19
	PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA  PixelFormat = 20
	PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA  PixelFormat = 21
)

// TextureFilter as declared in src/raylib.h:830
type TextureFilter int32

// TextureFilter enumeration from src/raylib.h:830
const (
	TEXTURE_FILTER_POINT           TextureFilter = iota
	TEXTURE_FILTER_BILINEAR        TextureFilter = 1
	TEXTURE_FILTER_TRILINEAR       TextureFilter = 2
	TEXTURE_FILTER_ANISOTROPIC_4X  TextureFilter = 3
	TEXTURE_FILTER_ANISOTROPIC_8X  TextureFilter = 4
	TEXTURE_FILTER_ANISOTROPIC_16X TextureFilter = 5
)

// TextureWrap as declared in src/raylib.h:838
type TextureWrap int32

// TextureWrap enumeration from src/raylib.h:838
const (
	TEXTURE_WRAP_REPEAT        TextureWrap = iota
	TEXTURE_WRAP_CLAMP         TextureWrap = 1
	TEXTURE_WRAP_MIRROR_REPEAT TextureWrap = 2
	TEXTURE_WRAP_MIRROR_CLAMP  TextureWrap = 3
)

// CubemapLayout as declared in src/raylib.h:848
type CubemapLayout int32

// CubemapLayout enumeration from src/raylib.h:848
const (
	CUBEMAP_LAYOUT_AUTO_DETECT         CubemapLayout = iota
	CUBEMAP_LAYOUT_LINE_VERTICAL       CubemapLayout = 1
	CUBEMAP_LAYOUT_LINE_HORIZONTAL     CubemapLayout = 2
	CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR CubemapLayout = 3
	CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE CubemapLayout = 4
	CUBEMAP_LAYOUT_PANORAMA            CubemapLayout = 5
)

// FontType as declared in src/raylib.h:855
type FontType int32

// FontType enumeration from src/raylib.h:855
const (
	FONT_DEFAULT FontType = iota
	FONT_BITMAP  FontType = 1
	FONT_SDF     FontType = 2
)

// BlendMode as declared in src/raylib.h:865
type BlendMode int32

// BlendMode enumeration from src/raylib.h:865
const (
	BLEND_ALPHA           BlendMode = iota
	BLEND_ADDITIVE        BlendMode = 1
	BLEND_MULTIPLIED      BlendMode = 2
	BLEND_ADD_COLORS      BlendMode = 3
	BLEND_SUBTRACT_COLORS BlendMode = 4
	BLEND_CUSTOM          BlendMode = 5
)

// Gestures as declared in src/raylib.h:881
type Gestures int32

// Gestures enumeration from src/raylib.h:881
const (
	GESTURE_NONE        Gestures = iota
	GESTURE_TAP         Gestures = 1
	GESTURE_DOUBLETAP   Gestures = 2
	GESTURE_HOLD        Gestures = 4
	GESTURE_DRAG        Gestures = 8
	GESTURE_SWIPE_RIGHT Gestures = 16
	GESTURE_SWIPE_LEFT  Gestures = 32
	GESTURE_SWIPE_UP    Gestures = 64
	GESTURE_SWIPE_DOWN  Gestures = 128
	GESTURE_PINCH_IN    Gestures = 256
	GESTURE_PINCH_OUT   Gestures = 512
)

// CameraMode as declared in src/raylib.h:890
type CameraMode int32

// CameraMode enumeration from src/raylib.h:890
const (
	CAMERA_CUSTOM       CameraMode = iota
	CAMERA_FREE         CameraMode = 1
	CAMERA_ORBITAL      CameraMode = 2
	CAMERA_FIRST_PERSON CameraMode = 3
	CAMERA_THIRD_PERSON CameraMode = 4
)

// CameraProjection as declared in src/raylib.h:896
type CameraProjection int32

// CameraProjection enumeration from src/raylib.h:896
const (
	CAMERA_PERSPECTIVE  CameraProjection = iota
	CAMERA_ORTHOGRAPHIC CameraProjection = 1
)

// NPatchLayout as declared in src/raylib.h:903
type NPatchLayout int32

// NPatchLayout enumeration from src/raylib.h:903
const (
	NPATCH_NINE_PATCH             NPatchLayout = iota
	NPATCH_THREE_PATCH_VERTICAL   NPatchLayout = 1
	NPATCH_THREE_PATCH_HORIZONTAL NPatchLayout = 2
)

// ShaderAttributeDataType as declared in src/rlgl.h:301
type ShaderAttributeDataType int32

// ShaderAttributeDataType enumeration from src/rlgl.h:301
const (
	SHADER_ATTRIB_FLOAT ShaderAttributeDataType = iota
	SHADER_ATTRIB_VEC2  ShaderAttributeDataType = 1
	SHADER_ATTRIB_VEC3  ShaderAttributeDataType = 2
	SHADER_ATTRIB_VEC4  ShaderAttributeDataType = 3
)
