// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 10 Sep 2020 10:51:00 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raylib provides Go bindings for Raylib.
*/
package raylib
