// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Sep 2020 11:05:38 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raylib provides Go bindings for Raylib.
*/
package raylib
