// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 09 Sep 2020 17:23:55 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raylib provides Go bindings for Raylib.
*/
package raylib
