// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 19 May 2021 16:09:31 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raylib

/*
#include "../lib/raygui/src/raygui.h"
#include "../lib/raygui/src/ricons.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// GuiStyleProp as declared in src/raygui.h:256
type gGuiStyleProp struct {
	gControlId     uint16
	gPropertyId    uint16
	gPropertyValue int32
	ref8760bcee    *C.GuiStyleProp
	allocs8760bcee interface{}
}
type GuiStyleProp struct {
	ControlId     uint16
	PropertyId    uint16
	PropertyValue int32
}
