// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 19 May 2021 16:09:31 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raygui provides Go bindings for Raygui.
*/
package raylib
