// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Jul 2020 16:18:40 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raylib

/*
#include "../lib/raylib/src/raylib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Vector2 as declared in src/raylib.h:176
type Vector2 struct {
	X              float32
	Y              float32
	ref29ca61a5    *C.Vector2
	allocs29ca61a5 interface{}
}

// Vector3 as declared in src/raylib.h:183
type Vector3 struct {
	X              float32
	Y              float32
	Z              float32
	ref5ecd5133    *C.Vector3
	allocs5ecd5133 interface{}
}

// Vector4 as declared in src/raylib.h:191
type Vector4 struct {
	X              float32
	Y              float32
	Z              float32
	W              float32
	refc0a9c490    *C.Vector4
	allocsc0a9c490 interface{}
}

// Quaternion as declared in src/raylib.h:194
type Quaternion struct {
	X              float32
	Y              float32
	Z              float32
	W              float32
	refc0a9c490    *C.Vector4
	allocsc0a9c490 interface{}
}

// Matrix as declared in src/raylib.h:202
type Matrix struct {
	M0             float32
	M4             float32
	M8             float32
	M12            float32
	M1             float32
	M5             float32
	M9             float32
	M13            float32
	M2             float32
	M6             float32
	M10            float32
	M14            float32
	M3             float32
	M7             float32
	M11            float32
	M15            float32
	refff9f44f9    *C.Matrix
	allocsff9f44f9 interface{}
}

// Color as declared in src/raylib.h:210
type Color struct {
	R              byte
	G              byte
	B              byte
	A              byte
	refa79767ed    *C.Color
	allocsa79767ed interface{}
}

// Rectangle as declared in src/raylib.h:218
type Rectangle struct {
	X              float32
	Y              float32
	Width          float32
	Height         float32
	refcee8783a    *C.Rectangle
	allocscee8783a interface{}
}

// Image as declared in src/raylib.h:228
type Image struct {
	Data          unsafe.Pointer
	Width         int32
	Height        int32
	Mipmaps       int32
	Format        int32
	ref4fc2b5b    *C.Image
	allocs4fc2b5b interface{}
}

// Texture2D as declared in src/raylib.h:238
type Texture2D struct {
	Id             uint32
	Width          int32
	Height         int32
	Mipmaps        int32
	Format         int32
	ref3c51a40b    *C.Texture2D
	allocs3c51a40b interface{}
}

// Texture as declared in src/raylib.h:241
type Texture struct {
	Id             uint32
	Width          int32
	Height         int32
	Mipmaps        int32
	Format         int32
	ref3c51a40b    *C.Texture2D
	allocs3c51a40b interface{}
}

// TextureCubemap as declared in src/raylib.h:244
type TextureCubemap struct {
	Id             uint32
	Width          int32
	Height         int32
	Mipmaps        int32
	Format         int32
	ref3c51a40b    *C.Texture2D
	allocs3c51a40b interface{}
}

// RenderTexture2D as declared in src/raylib.h:252
type RenderTexture2D struct {
	Id             uint32
	Texture        Texture2D
	Depth          Texture2D
	DepthTexture   bool
	ref2f94e9e3    *C.RenderTexture2D
	allocs2f94e9e3 interface{}
}

// RenderTexture as declared in src/raylib.h:255
type RenderTexture struct {
	Id             uint32
	Texture        Texture2D
	Depth          Texture2D
	DepthTexture   bool
	ref2f94e9e3    *C.RenderTexture2D
	allocs2f94e9e3 interface{}
}

// NPatchInfo as declared in src/raylib.h:265
type NPatchInfo struct {
	SourceRec      Rectangle
	Left           int32
	Top            int32
	Right          int32
	Bottom         int32
	Type           int32
	ref78104a03    *C.NPatchInfo
	allocs78104a03 interface{}
}

// CharInfo as declared in src/raylib.h:274
type CharInfo struct {
	Value          int32
	OffsetX        int32
	OffsetY        int32
	AdvanceX       int32
	Image          Image
	ref702c36c0    *C.CharInfo
	allocs702c36c0 interface{}
}

// Font as declared in src/raylib.h:283
type Font struct {
	BaseSize       int32
	CharsCount     int32
	Texture        Texture2D
	Recs           []Rectangle
	Chars          []CharInfo
	ref70a6a7ec    *C.Font
	allocs70a6a7ec interface{}
}

// Camera3D as declared in src/raylib.h:294
type Camera3D struct {
	Position      Vector3
	Target        Vector3
	Up            Vector3
	Fovy          float32
	Type          int32
	ref7b09036    *C.Camera3D
	allocs7b09036 interface{}
}

// Camera as declared in src/raylib.h:296
type Camera struct {
	Position      Vector3
	Target        Vector3
	Up            Vector3
	Fovy          float32
	Type          int32
	ref7b09036    *C.Camera3D
	allocs7b09036 interface{}
}

// Camera2D as declared in src/raylib.h:304
type Camera2D struct {
	Offset         Vector2
	Target         Vector2
	Rotation       float32
	Zoom           float32
	ref1eaba177    *C.Camera2D
	allocs1eaba177 interface{}
}

// Mesh as declared in src/raylib.h:330
type Mesh struct {
	VertexCount    int32
	TriangleCount  int32
	Vertices       []float32
	Texcoords      []float32
	Texcoords2     []float32
	Normals        []float32
	Tangents       []float32
	Colors         []byte
	Indices        []uint16
	AnimVertices   []float32
	AnimNormals    []float32
	BoneIds        []int32
	BoneWeights    []float32
	VaoId          uint32
	VboId          []uint32
	ref415d9568    *C.Mesh
	allocs415d9568 interface{}
}

// Shader as declared in src/raylib.h:336
type Shader struct {
	Id             uint32
	Locs           []int32
	reff85f9b1e    *C.Shader
	allocsf85f9b1e interface{}
}

// MaterialMap as declared in src/raylib.h:343
type MaterialMap struct {
	Texture        Texture2D
	Color          Color
	Value          float32
	refa8350ad3    *C.MaterialMap
	allocsa8350ad3 interface{}
}

// Material as declared in src/raylib.h:350
type Material struct {
	Shader         Shader
	Maps           []MaterialMap
	Params         []float32
	ref85c817c3    *C.Material
	allocs85c817c3 interface{}
}

// Transform as declared in src/raylib.h:357
type Transform struct {
	Translation    Vector3
	Rotation       Quaternion
	Scale          Vector3
	reff543030e    *C.Transform
	allocsf543030e interface{}
}

// BoneInfo as declared in src/raylib.h:363
type BoneInfo struct {
	Name           [32]byte
	Parent         int32
	ref5ab7f197    *C.BoneInfo
	allocs5ab7f197 interface{}
}

// Model as declared in src/raylib.h:380
type Model struct {
	Transform      Matrix
	MeshCount      int32
	Meshes         []Mesh
	MaterialCount  int32
	Materials      []Material
	MeshMaterial   []int32
	BoneCount      int32
	Bones          []BoneInfo
	BindPose       []Transform
	ref16545ddd    *C.Model
	allocs16545ddd interface{}
}

// ModelAnimation as declared in src/raylib.h:389
type ModelAnimation struct {
	BoneCount      int32
	Bones          []BoneInfo
	FrameCount     int32
	FramePoses     [][]Transform
	ref26dd6a24    *C.ModelAnimation
	allocs26dd6a24 interface{}
}

// Ray as declared in src/raylib.h:395
type Ray struct {
	Position       Vector3
	Direction      Vector3
	refc546b0b2    *C.Ray
	allocsc546b0b2 interface{}
}

// RayHitInfo as declared in src/raylib.h:403
type RayHitInfo struct {
	Hit            bool
	Distance       float32
	Position       Vector3
	Normal         Vector3
	refb8de43a9    *C.RayHitInfo
	allocsb8de43a9 interface{}
}

// BoundingBox as declared in src/raylib.h:409
type BoundingBox struct {
	Min            Vector3
	Max            Vector3
	refa54e9d16    *C.BoundingBox
	allocsa54e9d16 interface{}
}

// Wave as declared in src/raylib.h:418
type Wave struct {
	SampleCount    uint32
	SampleRate     uint32
	SampleSize     uint32
	Channels       uint32
	Data           unsafe.Pointer
	ref7a3602b7    *C.Wave
	allocs7a3602b7 interface{}
}

// RAudioBuffer as declared in src/raylib.h:420
type RAudioBuffer C.rAudioBuffer

// AudioStream as declared in src/raylib.h:430
type AudioStream struct {
	SampleRate     uint32
	SampleSize     uint32
	Channels       uint32
	Buffer         []RAudioBuffer
	ref997374a2    *C.AudioStream
	allocs997374a2 interface{}
}

// Sound as declared in src/raylib.h:436
type Sound struct {
	SampleCount    uint32
	Stream         AudioStream
	ref394fec80    *C.Sound
	allocs394fec80 interface{}
}

// Music as declared in src/raylib.h:448
type Music struct {
	CtxType       int32
	CtxData       unsafe.Pointer
	Looping       bool
	SampleCount   uint32
	Stream        AudioStream
	refc930d4e    *C.Music
	allocsc930d4e interface{}
}

// VrDeviceInfo as declared in src/raylib.h:462
type VrDeviceInfo struct {
	HResolution            int32
	VResolution            int32
	HScreenSize            float32
	VScreenSize            float32
	VScreenCenter          float32
	EyeToScreenDistance    float32
	LensSeparationDistance float32
	InterpupillaryDistance float32
	LensDistortionValues   [4]float32
	ChromaAbCorrection     [4]float32
	ref6e24e41d            *C.VrDeviceInfo
	allocs6e24e41d         interface{}
}

// Va_list type as declared in include/stdarg.h:30
type Va_list unsafe.Pointer

// __gnuc_va_list type as declared in include/stdarg.h:48
type __gnuc_va_list unsafe.Pointer
