// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 22 Apr 2021 21:48:52 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../lib/raylib/src/physac.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

