// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 06 Aug 2020 17:09:59 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../lib/raylib/src/physac.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

