// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 19 May 2021 16:47:18 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package physac

/*
#include "../lib/raylib/src/physac.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// PHYSAC_DEFINE_VECTOR2_TYPE as defined in go-raylib/<predefine>:24
	PHYSAC_DEFINE_VECTOR2_TYPE = 1
	// PHYSAC_STATIC as defined in go-raylib/<predefine>:25
	PHYSAC_STATIC = 1
	// PHYSAC_MAX_BODIES as defined in src/physac.h:111
	PHYSAC_MAX_BODIES = 64
	// PHYSAC_MAX_MANIFOLDS as defined in src/physac.h:112
	PHYSAC_MAX_MANIFOLDS = 4096
	// PHYSAC_MAX_VERTICES as defined in src/physac.h:113
	PHYSAC_MAX_VERTICES = 24
	// PHYSAC_DEFAULT_CIRCLE_VERTICES as defined in src/physac.h:114
	PHYSAC_DEFAULT_CIRCLE_VERTICES = 24
	// PHYSAC_COLLISION_ITERATIONS as defined in src/physac.h:116
	PHYSAC_COLLISION_ITERATIONS = 100
	// PHYSAC_PENETRATION_ALLOWANCE as defined in src/physac.h:117
	PHYSAC_PENETRATION_ALLOWANCE = 0.05
	// PHYSAC_PENETRATION_CORRECTION as defined in src/physac.h:118
	PHYSAC_PENETRATION_CORRECTION = 0.4
	// PHYSAC_PI as defined in src/physac.h:120
	PHYSAC_PI = 3.14159265358979323846
	// PHYSAC_DEG2RAD as defined in src/physac.h:121
	PHYSAC_DEG2RAD = (PHYSAC_PI / 180.0)
)

// PhysicsShapeType as declared in src/physac.h:130
type PhysicsShapeType int32

// PhysicsShapeType enumeration from src/physac.h:130
const (
	PHYSICS_CIRCLE  PhysicsShapeType = iota
	PHYSICS_POLYGON PhysicsShapeType = 1
)
