// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 21 Mar 2021 14:52:01 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package physac provides Go bindings for Physac.
*/
package physac
