// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 19 May 2021 16:47:18 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package physac

/*
#include "../lib/raylib/src/physac.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// InitPhysics function as declared in src/physac.h:215
func InitPhysics() {
	C.InitPhysics()
}

// UpdatePhysics function as declared in src/physac.h:216
func UpdatePhysics() {
	C.UpdatePhysics()
}

// ResetPhysics function as declared in src/physac.h:217
func ResetPhysics() {
	C.ResetPhysics()
}

// ClosePhysics function as declared in src/physac.h:218
func ClosePhysics() {
	C.ClosePhysics()
}

// SetPhysicsTimeStep function as declared in src/physac.h:219
func SetPhysicsTimeStep(delta float64) {
	cdelta, _ := (C.double)(delta), cgoAllocsUnknown
	C.SetPhysicsTimeStep(cdelta)
}

// SetPhysicsGravity function as declared in src/physac.h:220
func SetPhysicsGravity(x float32, y float32) {
	cx, _ := (C.float)(x), cgoAllocsUnknown
	cy, _ := (C.float)(y), cgoAllocsUnknown
	C.SetPhysicsGravity(cx, cy)
}

// CreatePhysicsBodyCircle function as declared in src/physac.h:223
func CreatePhysicsBodyCircle(pos Vector2, radius float32, density float32) *PhysicsBodyData {
	cpos, _ := *(*C.Vector2)(unsafe.Pointer(&pos)), cgoAllocsUnknown
	cradius, _ := (C.float)(radius), cgoAllocsUnknown
	cdensity, _ := (C.float)(density), cgoAllocsUnknown
	__ret := C.CreatePhysicsBodyCircle(cpos, cradius, cdensity)
	__v := newPhysicsBodyDataRef(unsafe.Pointer(__ret)).convert()
	return __v
}

// CreatePhysicsBodyRectangle function as declared in src/physac.h:224
func CreatePhysicsBodyRectangle(pos Vector2, width float32, height float32, density float32) *PhysicsBodyData {
	cpos, _ := *(*C.Vector2)(unsafe.Pointer(&pos)), cgoAllocsUnknown
	cwidth, _ := (C.float)(width), cgoAllocsUnknown
	cheight, _ := (C.float)(height), cgoAllocsUnknown
	cdensity, _ := (C.float)(density), cgoAllocsUnknown
	__ret := C.CreatePhysicsBodyRectangle(cpos, cwidth, cheight, cdensity)
	__v := newPhysicsBodyDataRef(unsafe.Pointer(__ret)).convert()
	return __v
}

// CreatePhysicsBodyPolygon function as declared in src/physac.h:225
func CreatePhysicsBodyPolygon(pos Vector2, radius float32, sides int32, density float32) *PhysicsBodyData {
	cpos, _ := *(*C.Vector2)(unsafe.Pointer(&pos)), cgoAllocsUnknown
	cradius, _ := (C.float)(radius), cgoAllocsUnknown
	csides, _ := (C.int)(sides), cgoAllocsUnknown
	cdensity, _ := (C.float)(density), cgoAllocsUnknown
	__ret := C.CreatePhysicsBodyPolygon(cpos, cradius, csides, cdensity)
	__v := newPhysicsBodyDataRef(unsafe.Pointer(__ret)).convert()
	return __v
}

// DestroyPhysicsBody function as declared in src/physac.h:226
func DestroyPhysicsBody(body *PhysicsBodyData) {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	C.DestroyPhysicsBody(cbody)
}

// PhysicsAddForce function as declared in src/physac.h:229
func PhysicsAddForce(body *PhysicsBodyData, force Vector2) {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	cforce, _ := *(*C.Vector2)(unsafe.Pointer(&force)), cgoAllocsUnknown
	C.PhysicsAddForce(cbody, cforce)
}

// PhysicsAddTorque function as declared in src/physac.h:230
func PhysicsAddTorque(body *PhysicsBodyData, amount float32) {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	camount, _ := (C.float)(amount), cgoAllocsUnknown
	C.PhysicsAddTorque(cbody, camount)
}

// PhysicsShatter function as declared in src/physac.h:231
func PhysicsShatter(body *PhysicsBodyData, position Vector2, force float32) {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	cposition, _ := *(*C.Vector2)(unsafe.Pointer(&position)), cgoAllocsUnknown
	cforce, _ := (C.float)(force), cgoAllocsUnknown
	C.PhysicsShatter(cbody, cposition, cforce)
}

// SetPhysicsBodyRotation function as declared in src/physac.h:232
func SetPhysicsBodyRotation(body *PhysicsBodyData, radians float32) {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	cradians, _ := (C.float)(radians), cgoAllocsUnknown
	C.SetPhysicsBodyRotation(cbody, cradians)
}

// GetPhysicsBody function as declared in src/physac.h:235
func GetPhysicsBody(index int32) *PhysicsBodyData {
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.GetPhysicsBody(cindex)
	__v := newPhysicsBodyDataRef(unsafe.Pointer(__ret)).convert()
	return __v
}

// GetPhysicsBodiesCount function as declared in src/physac.h:236
func GetPhysicsBodiesCount() int32 {
	__ret := C.GetPhysicsBodiesCount()
	__v := (int32)(__ret)
	return __v
}

// GetPhysicsShapeType function as declared in src/physac.h:237
func GetPhysicsShapeType(index int32) int32 {
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.GetPhysicsShapeType(cindex)
	__v := (int32)(__ret)
	return __v
}

// GetPhysicsShapeVerticesCount function as declared in src/physac.h:238
func GetPhysicsShapeVerticesCount(index int32) int32 {
	cindex, _ := (C.int)(index), cgoAllocsUnknown
	__ret := C.GetPhysicsShapeVerticesCount(cindex)
	__v := (int32)(__ret)
	return __v
}

// GetPhysicsShapeVertex function as declared in src/physac.h:239
func GetPhysicsShapeVertex(body *PhysicsBodyData, vertex int32) Vector2 {
	cbody, _ := (*C.PhysicsBodyData)(unsafe.Pointer(body)), cgoAllocsUnknown
	cvertex, _ := (C.int)(vertex), cgoAllocsUnknown
	__ret := C.GetPhysicsShapeVertex(cbody, cvertex)
	__v := *newVector2Ref(unsafe.Pointer(&__ret)).convert()
	return __v
}
