// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Jun 2021 11:52:25 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package rres

/*
#include "../lib/rres/src/rres.h"
#include "../lib/rres/src/rres-raylib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// RRES_CURRENT_VERSION as defined in src/rres.h:91
	RRES_CURRENT_VERSION = 100
)

// RresDataType as declared in src/rres.h:167
type RresDataType int32

// RresDataType enumeration from src/rres.h:167
const (
	RRES_DATA_RAW       RresDataType = 1
	RRES_DATA_TEXT      RresDataType = 2
	RRES_DATA_IMAGE     RresDataType = 3
	RRES_DATA_WAVE      RresDataType = 4
	RRES_DATA_VERTEX    RresDataType = 5
	RRES_DATA_FONT_INFO RresDataType = 6
	RRES_DATA_DIRECTORY RresDataType = 100
)
